import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Users App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex content-center justify-center flex-wrap bg-gray-200 h-screen mx-0 my-0 overflow-hidden">
        Hello App
      </main>
    </div>
  )
}
